### ISSUE TITLE
Repositórios divergentes do ppgccufmg

### ISSUE THREAD

**Issue by vilarneto** [verlab/ppgccufmg#2]
Olá pessoal, tudo bem? Sou o Vilar, criador original do pacote `ppgccufmg`.

Vi este repositório, e achei bacana que o pacote continua evoluindo! Apenas fico preocupado com a divergência de versionamento e arquivos em relação ao meu repositório original, que se encontra [no Bitbucket](https://bitbucket.org/vilarneto/ppgccufmg/): lá o pacote acabou de ser atualizado para a versão 1.52 e a cronologia começa a ficar diferente da deste repositório – ou seja, o que este repositório chama de “latest version” na verdade é um “fork”.

Uma sugestão: Que tal fazermos o merge dos nossos repositórios e manter todos os ponteiros para [o meu site](https://vilarneto.com/ppgccufmg)? Assim a gente mantém um único ponto de chegada para todos os que querem baixar o pacote. Eu continuo fazendo a manutenção dos arquivos com todo o prazer!

Abraços,

-- 
Vilar

**Comment by leokassio** [comment]
olá Vilar,
muito boa a sua preocupação e intenção. Eu estou tendo muitos problemas para submeter a minha tese porque aparentemente usei uma versão antiga que não está em conformidade com as diretrizes atuais da UFMG. 
Decidi tentar a sua versão mais nova mas o link está quebrado, tem como vc ajudar com isso? Muito obrigado.

**Comment by vilarneto** [comment]
Oi @leokassio, tudo bem?

Há algum tempo houve uma reestruturação grande do modelo de teses e dissertações, e já recebi a manifestação de algumas pessoas sobre essas divergências do modelo LaTeX.

Acabou que com o tempo a gente não conseguiu encontrar uma maneira de colaborar para atualizar esse modelo. Como consequência, essa versão “minha” (cujo link você corretamente disse que está quebrado) começou a confundir os alunos: é mais nova, porém inadequada — por isso eu decidi desabilitar o meu repositório para não continuar distribuindo um pacote que não corresponde mais ao layout oficial.

Para quem quiser adotar a missão de adaptar a classe às diretrizes atuais, eu ofereço de bom grado todo o código-fonte! Porém, para a utilização como usuário final a classe está longe de ser adequada, então acho que não consigo ajudá-lo nesse sentido, ok?

Um abração!

**Comment by leokassio** [comment]
que pena, muito obrigado @vilarneto

**Comment by h3ct0r** [comment]
Olá @vilarneto , acabei de fazer um PR para atualizar aqui a ultima versão do template v1.60 que você tinha publicado no seu BitBucket (https://bitbucket.org/vilarneto/ppgccufmg/issues?status=new&status=open). Como vou defender dentro de pouco, vou fazer as modificações necessárias para adequar o template ao padrão novo da UFMG e colocá-las nesse repo do VerLab (v1.70?). 

Neste sentido, você teria disponível também as fontes LaTeX do PDF de documentação? não vi ele nos arquivos que foram disponibilizados.

Obrigado ter disponibilizado o template e dado todo esse suporte!

**Comment by ericksonrn** [comment]
Muito obrigado pela dica Erickson, realmente está confuso mesmo! Vou entrar
em contato com o Washington!

[]'s

**Comment by ericksonrn** [comment]
Olá Hector,

Tem uma confusão danada com as últimas mudanças.

Procure o Washington. Ele usou recentemente uma versão que deve se tornar o
padrão do programa e que foi aceita pelo repositório e pela biblioteca.

Abraço,

Erickson Nascimento
